---
title: "Homework 05"
author: "Spencer Pease"
date: "11/11/2019"
output:
  pdf_document:
    template: default.latex
---

```{r setup, include=FALSE}

# Set output options
knitr::opts_chunk$set(echo = FALSE)
options(knitr.kable.NA = '-')

# Include libraries
library(magrittr)
library(kableExtra)

# Helper functions
source("functions/output_mri_table.R")

# Prepare data
mri <-
  read.table("data/mri.txt", header = TRUE) %>%
  dplyr::as_tibble() %>%
  dplyr::filter(!is.na(.data$crt)) %>%
  dplyr::transmute(
    surv_5yr = dplyr::if_else(.data$obstime >= 5 * 365.25, 1, 0),
    high_crt = dplyr::if_else(.data$crt > 1.2, 1, 0)
  )

```


# _(Q1)_ Prospective Association Analysis

```{r contingency-table-count}

mri_table <- xtabs(~surv_5yr + high_crt, data = mri)

# tmp <- prop.table(mri_table, 2) %>% addmargins()

output_mri_table(
  mri_table,
  "Contingency table for creatinine level and survival status."
)

```

```{r contingency-table-prob}

mri_prob_by_crt <- addmargins(prop.table(mri_table, 2))


```


# _(Q2)_ Retrospective Association Analysis



# _(Q3)_ Risk of Death
